#line 2 "parser/lex.yy.c"

#line 4 "parser/lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 49
#define YY_END_OF_BUFFER 50
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[190] =
    {   0,
        0,    0,   42,   42,   46,   46,   50,   48,   40,   27,
       16,   28,   38,    8,    9,   14,   12,   24,   13,   37,
       15,    3,    2,   35,   34,   19,   18,   20,   39,   10,
       11,   30,    1,   29,   31,   42,   40,   27,   16,   28,
       38,    8,    9,   14,   12,   24,   13,   37,   15,    3,
        2,   35,   34,   19,   18,   20,   39,   10,   11,   30,
        1,   29,   31,   46,   47,   27,   16,   28,   38,    8,
        9,   14,   12,   24,   13,   37,   15,    3,    2,   35,
       34,   19,   18,   20,   39,   10,   11,   30,    1,   29,
       31,   23,   25,    0,    0,   36,   41,   45,    0,    3,

        5,    0,    0,    2,    2,   17,   33,   21,   22,   32,
       39,   26,   42,   23,   25,   42,   42,   43,   43,   44,
       36,   42,   42,    3,    5,   42,   42,    2,    2,   17,
       33,   21,   22,   32,   39,   26,   46,   23,   25,   46,
       46,   36,   41,   45,   46,    3,    5,   46,   46,    2,
        2,   17,   33,   21,   22,   32,   39,   26,    0,    6,
        0,    6,    5,    0,    5,    4,   42,    6,   42,    6,
        5,   42,    5,    4,   46,    6,   46,    6,    5,   46,
        5,    4,    7,    7,    7,    7,    7,    7,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    1,    1,    1,    4,    5,    6,    7,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   16,
       16,   16,   16,   16,   16,   17,   17,   18,   19,   20,
       21,   22,    1,    1,   23,   23,   23,   23,   24,   23,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   26,   25,   25,
       27,   28,   29,   30,   25,    1,   23,   23,   23,   23,

       24,   23,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   31,
       25,   25,   32,   33,    1,   34,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[35] =
    {   0,
        1,    2,    1,    1,    1,    3,    1,    1,    4,    1,
        1,    1,    1,    1,    5,    5,    5,    1,    1,    1,
        1,    1,    5,    5,    5,    5,    1,    1,    1,    1,
        5,    1,    1,    1
    } ;

static yyconst flex_uint16_t yy_base[200] =
    {   0,
        0,    0,   34,    0,   68,    0,  281,  450,  450,  258,
      450,  269,  228,  450,  450,  450,  450,  450,  450,  242,
       94,   96,  117,  223,  450,   84,  450,   85,    0,  450,
      450,  450,  450,  205,  450,    0,    0,  192,    0,  192,
      108,    0,    0,  101,    0,    0,    0,  183,  107,  138,
      109,  173,    0,   98,    0,  116,  157,    0,    0,    0,
        0,  157,    0,    0,  450,  166,    0,  181,  137,    0,
        0,    0,    0,    0,    0,  165,  114,  176,  130,  149,
        0,  128,    0,  136,  195,    0,    0,    0,    0,  119,
        0,  450,  450,  138,  157,  450,  450,  450,  160,  153,

      144,  189,  199,  151,    0,  450,  450,  450,  450,  450,
        0,  450,    0,    0,    0,  189,  218,  128,  194,  450,
        0,    0,  213,  205,  217,  225,  234,  237,  244,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,  260,
      263,    0,    0,    0,  256,  208,  261,  268,  278,  281,
      288,    0,    0,    0,    0,    0,    0,    0,  219,  450,
      239,  258,  293,  305,  308,  312,  309,    0,  324,  325,
      323,  326,  329,  334,  353,    0,  358,  359,  351,  354,
      357,  373,  450,  283,    0,  370,    0,  376,  450,  404,
      126,  409,  414,  419,  424,  429,  434,  439,  444

    } ;

static yyconst flex_int16_t yy_def[200] =
    {   0,
      189,    1,  189,    3,  189,    5,  189,  189,  189,  189,
      189,  189,  190,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  191,  189,
      189,  189,  189,  189,  189,  192,  192,  192,  192,  192,
      193,  192,  192,  194,  192,  192,  192,  192,  192,  192,
       50,  192,  192,  192,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  195,  189,  195,  195,  195,  196,  195,
      195,  195,  195,  195,  195,  195,  195,  195,   78,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  189,  189,  197,  197,  189,  189,  189,  189,   22,

      100,  189,  189,   23,   23,  189,  189,  189,  189,  189,
      191,  189,  192,  192,  192,  198,  198,  194,  194,  189,
      192,  192,  192,   50,   50,  192,  192,   50,   50,  192,
      192,  192,  192,  192,   57,  192,  195,  195,  195,  199,
      199,  195,  195,  195,  195,   78,   78,  195,  195,   78,
       78,  195,  195,  195,  195,  195,   85,  195,  197,  189,
      197,  197,  189,  189,  189,  189,  198,  192,  198,  198,
      192,  192,  192,  192,  199,  195,  199,  199,  195,  195,
      195,  195,  189,  197,  192,  198,  195,  199,    0,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  189

    } ;

static yyconst flex_uint16_t yy_nxt[485] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   20,   21,   22,   23,   23,   24,   25,   26,
       27,   28,   29,   29,   29,   29,   30,    8,   31,   32,
       29,   33,   34,   35,   36,   37,   38,   39,   40,   41,
       42,   43,   44,   45,   46,   47,   48,   49,   50,   51,
       51,   52,   53,   54,   55,   56,   57,   57,   57,   57,
       58,   36,   59,   60,   57,   61,   62,   63,   64,   65,
       66,   67,   68,   69,   70,   71,   72,   73,   74,   75,
       76,   77,   78,   79,   79,   80,   81,   82,   83,   84,
       85,   85,   85,   85,   86,   64,   87,   88,   85,   89,

       90,   91,   97,  107,  108,  109,  110,   98,   99,  119,
      100,  100,  101,  113,  120,   97,   94,  131,  132,  102,
      122,  103,  143,  128,  129,  129,  103,  144,  102,   99,
      111,  104,  105,  105,  113,  117,  133,  134,   94,  113,
      102,  189,  137,  160,  150,  151,  151,  153,  154,  102,
      123,  158,  124,  124,  125,  137,  155,  156,  101,  101,
      137,  126,  162,  127,  141,  161,  104,  104,  127,  152,
      126,  135,  135,  135,  163,  163,  163,  142,  189,  135,
      135,  135,  135,  189,  161,  139,  138,  135,  145,  136,
      146,  146,  147,  130,  168,  121,  115,  159,  164,  148,

      164,  149,  119,  165,  165,  165,  149,  189,  148,  157,
      157,  157,  114,  166,  166,  166,  169,  157,  157,  157,
      157,  166,  166,  170,  183,  157,  159,  171,  171,  171,
      113,  125,  125,  137,  172,  113,  172,  112,  137,  173,
      173,  173,  113,  106,  184,  169,  161,  113,  174,  174,
      174,  128,  128,  128,   96,   95,  174,  174,  128,  129,
      129,  159,  113,  160,  159,  176,  161,  113,  178,  113,
      179,  179,  179,   93,  113,  147,  147,  180,   92,  180,
      189,  189,  181,  181,  181,  161,  137,  177,  183,  189,
      177,  137,  182,  182,  182,  150,  150,  150,  189,  189,

      182,  182,  150,  151,  151,  189,  137,  163,  163,  163,
      161,  137,  189,  137,  185,  189,  102,  159,  137,  165,
      165,  165,  165,  165,  165,  102,  166,  166,  166,  186,
      168,  189,  159,  159,  166,  166,  169,  171,  171,  171,
      173,  173,  173,  173,  173,  173,  126,  189,  174,  174,
      174,  169,  169,  189,  159,  126,  174,  174,  187,  159,
      159,  189,  189,  188,  176,  179,  179,  179,  181,  181,
      181,  181,  181,  181,  148,  185,  189,  159,  159,  189,
      177,  187,  189,  148,  189,  177,  177,  182,  182,  182,
      189,  189,  189,  189,  189,  182,  182,  169,  189,  189,

      189,  189,  189,  177,   94,   94,  189,   94,   94,  113,
      113,  113,  189,  113,  116,  116,  116,  116,  116,  118,
      118,  118,  118,  118,  137,  189,  137,  137,  137,  140,
      140,  140,  140,  140,  159,  159,  159,  159,  159,  167,
      167,  167,  167,  167,  175,  175,  175,  175,  175,    7,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189
    } ;

static yyconst flex_int16_t yy_chk[485] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,

        5,    5,   21,   26,   26,   28,   28,   21,   22,   44,
       22,   22,   22,   41,   44,   49,   41,   54,   54,   22,
       49,   22,   77,   51,   51,   51,   22,   77,   22,   23,
      191,   23,   23,   23,   51,   41,   56,   56,   69,   51,
       23,  118,   69,   94,   79,   79,   79,   82,   82,   23,
       50,   90,   50,   50,   50,   79,   84,   84,  101,  101,
       79,   50,   95,   50,   69,   94,  104,  104,   50,   80,
       50,   57,   57,   57,   99,   99,   99,   76,  100,   57,
       57,   57,   57,  100,   95,   68,   66,   57,   78,   62,
       78,   78,   78,   52,  116,   48,   40,  116,  102,   78,

      102,   78,  119,  102,  102,  102,   78,  119,   78,   85,
       85,   85,   38,  103,  103,  103,  116,   85,   85,   85,
       85,  103,  103,  117,  159,   85,  117,  123,  123,  123,
      124,  125,  125,  146,  126,  124,  126,   34,  146,  126,
      126,  126,  125,   24,  161,  117,  159,  125,  127,  127,
      127,  128,  128,  128,   20,   13,  127,  127,  129,  129,
      129,  140,  128,  162,  141,  140,  161,  128,  141,  129,
      145,  145,  145,   12,  129,  147,  147,  148,   10,  148,
        7,    0,  148,  148,  148,  162,  147,  140,  184,    0,
      141,  147,  149,  149,  149,  150,  150,  150,    0,    0,

      149,  149,  151,  151,  151,    0,  150,  163,  163,  163,
      184,  150,    0,  151,  167,    0,  163,  167,  151,  164,
      164,  164,  165,  165,  165,  163,  166,  166,  166,  169,
      170,    0,  169,  170,  166,  166,  167,  171,  171,  171,
      172,  172,  172,  173,  173,  173,  171,    0,  174,  174,
      174,  169,  170,    0,  175,  171,  174,  174,  175,  177,
      178,    0,    0,  177,  178,  179,  179,  179,  180,  180,
      180,  181,  181,  181,  179,  186,    0,  188,  186,    0,
      175,  188,    0,  179,    0,  177,  178,  182,  182,  182,
        0,    0,    0,    0,    0,  182,  182,  186,    0,    0,

        0,    0,    0,  188,  190,  190,    0,  190,  190,  192,
      192,  192,    0,  192,  193,  193,  193,  193,  193,  194,
      194,  194,  194,  194,  195,    0,  195,  195,  195,  196,
      196,  196,  196,  196,  197,  197,  197,  197,  197,  198,
      198,  198,  198,  198,  199,  199,  199,  199,  199,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "parser/spl.l"
#line 2 "parser/spl.l"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include "../common.h"

#include "rule.h"

int Keytable_size = 0;

/* number of line. */
extern int line_no;
/* position of line. */
extern int line_pos;
/* buffer of current line. */
extern char line_buf[];

extern YYSTYPE yylval;
/* 是否把匹配到的文本输出 */
extern int dump_source;
/* 是否把匹配的TOKEN输出 */
extern int dump_token;

/* 判断是标识符还是关键字 */
static int id_or_keyword(char *lex);

/* 拷贝匹配到的内容到line_buf（结束标记'\0'），
 重新计算line_pos时需要删除结束标记'\0' */
#define DUMP_SOURCE if(dump_source) ECHO; \
						if (line_pos + strlen(yytext) < MAX_LINE_LENGTH) \
							memmove(line_buf + line_pos, yytext, strlen(yytext) + 1); \
						line_pos += strlen(yytext);

static char tmp[NAME_LEN];

#line 670 "parser/lex.yy.c"

#define INITIAL 0
#define star_slash_comment 1
#define slash_slash_comment 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 45 "parser/spl.l"

#line 892 "parser/lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 190 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 450 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 46 "parser/spl.l"
{
	int c;
	
	/* 检查块结果 */
	while ((c = input()))
	{
		if (c == '}')
		{
			break;
		}
		else if (c == '\n')
		{
			line_no ++;
		}
	}

	if (c == EOF)
		parse_error("Unexpected EOF.","");
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 66 "parser/spl.l"
{
	DUMP_SOURCE

	/* 将字符串转化成十进制数字 */
	yylval.num = stoi(yytext, 10);

	if (dump_token)
	{
		printf("token: cINTEGER, yylval.num = %d.\n", yylval.num);
	}
	return cINTEGER;
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 79 "parser/spl.l"
{
	DUMP_SOURCE

	/* 将字符串转化成十进制数字 */
	yylval.num = stoi(yytext, 8);

	if (dump_token)
	{
		printf("token: cINTEGER, yylval.num = %d.\n", yylval.num);
	}
	return cINTEGER;
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 92 "parser/spl.l"
{
	DUMP_SOURCE

	/* 将字符串转化成十进制数字 */
	yylval.num = stoi(yytext, 16);

	if (dump_token)
	{
		printf("token: cINTEGER, yylval.num = %d.\n", yylval.num);
	}
	return cINTEGER;
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 105 "parser/spl.l"
{
	/* 1.1E+1 or 1.1E-1*/
	DUMP_SOURCE

	/* 函数原型char *strncpy(char *dest, char *src, int size_t n);
	 复制字符串src中的内容到字符串dest中，复制多少由size_t n的值决定。
	 如果src的前n个字符不含NULL字符，则结果不会以NULL字符结束。
	 如果n < src的长度，只是将src的前n个字符复制到dest的前n个字符，不自动添加'\0'，也就是结果dest不包括'\0'，需要再手动添加一个'\0'。
	 如果src的长度小于n个字节，则以NULL填充dest直到复制完n个字节。
	 src和dest所指内存区域不可以重叠且dest必须有足够的空间来容纳src的字符长度+'\0'。 */
	strncpy(yylval.p_char, yytext, NAME_LEN);

	if (dump_token)
	{
		printf("token: cREAL, yylval.p_char = %s.\n", yylval.p_char);
	}
	return cREAL;
}
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 124 "parser/spl.l"
{
	/* Note that inside of a character class, all regular expression operators lose their special meaning 
	 except escape '\' and the character class operators, '-', '[', ']', and, at the beginning of the class '^'.
	 int this case, 起始和结束字符串必须是'，中间可以出现除了字符'之外的所有字符。 */

	DUMP_SOURCE

	strncpy(yylval.p_char, yytext, NAME_LEN);

	if (dump_token)
	{
		printf("token: cCHAR, yylval.p_char = %s.\n", yylval.p_char);
	}
	return cCHAR;
}
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 140 "parser/spl.l"
{
	DUMP_SOURCE

	int i;
	for(i = 1; i < strlen(yytext) - 1; i++)
	{
		tmp[i - 1] = yytext[i];
	}
	tmp[i - 1] = '\0';

	strncpy(yylval.p_char, tmp, NAME_LEN);

	if (dump_token)
	{
		printf("token: cSTRING, yylval.p_char = %s.\n", yylval.p_char);
	}
	return cSTRING;
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 159 "parser/spl.l"
{ 
	DUMP_SOURCE 

	if (dump_token)
	{
		printf("token: oLP.\n");
	}
	return oLP; 
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 169 "parser/spl.l"
{ 
	DUMP_SOURCE 

	if (dump_token)
	{
		printf("token: oRP.\n");
	}
	return oRP; 
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 180 "parser/spl.l"
{ 
	DUMP_SOURCE 
	
	if (dump_token)
	{
		printf("token: oLB.\n");
	}
	return oLB; 
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 190 "parser/spl.l"
{ 
	DUMP_SOURCE 
	
	if (dump_token)
	{
		printf("token: oRB.\n");
	}
	return oRB; 
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 200 "parser/spl.l"
{ 
	DUMP_SOURCE 
	
	if (dump_token)
	{
		printf("token: oPLUS.\n");
	}
	return oPLUS; 
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 210 "parser/spl.l"
{ 
	DUMP_SOURCE 
	
	if (dump_token)
	{
		printf("token: oMINUS.\n");
	}
	return oMINUS; 
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 220 "parser/spl.l"
{ 
	DUMP_SOURCE 
	
	if (dump_token)
	{
		printf("token: oMUL.\n");
	}
	return oMUL; 
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 230 "parser/spl.l"
{ 
	DUMP_SOURCE 
	
	if (dump_token)
	{
		printf("token: oDIV.\n");
	}
	return oDIV; 
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 240 "parser/spl.l"
{ 
	DUMP_SOURCE 
	
	if (dump_token)
	{
		printf("token: oMOD.\n");
	}
	return oMOD; 
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 250 "parser/spl.l"
{ 
	DUMP_SOURCE 
	
	if (dump_token)
	{
		printf("token: oASSIGN.\n");
	}
	return oASSIGN; 
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 260 "parser/spl.l"
{ 
	DUMP_SOURCE 
	
	if (dump_token)
	{
		printf("token: oEQUAL.\n");
	}
	return oEQUAL; 
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 270 "parser/spl.l"
{ 
	DUMP_SOURCE 
	
	if (dump_token)
	{
		printf("token: oLT.\n");
	}
	return oLT; 
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 280 "parser/spl.l"
{ 
	DUMP_SOURCE 
	
	if (dump_token)
	{
		printf("token: oGT.\n");
	}
	return oGT; 
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 290 "parser/spl.l"
{ 
	DUMP_SOURCE 
	
	if (dump_token)
	{
		printf("token: oLE.\n");
	}
	return oLE; 
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 300 "parser/spl.l"
{ 
	DUMP_SOURCE 
	
	if (dump_token)
	{
		printf("token: oGE.\n");
	}
	return oGE; 
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 310 "parser/spl.l"
{ 
	DUMP_SOURCE 
	
	if (dump_token)
	{
		printf("token: oUNEQU.\n");
	}
	return oUNEQU; 
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 320 "parser/spl.l"
{ 
	DUMP_SOURCE 
	if (dump_token)
	{
		printf("token: oCOMMA.\n");
	}
	return oCOMMA; 
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 330 "parser/spl.l"
{ 
	DUMP_SOURCE 
	
	if (dump_token)
	{
		printf("token: oAND.\n");
	}
	return oAND; 
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 340 "parser/spl.l"
{ 
	DUMP_SOURCE 
	
	if (dump_token)
	{
		printf("token: oOR.\n");
	}
	return oOR; 
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 350 "parser/spl.l"
{ 
	DUMP_SOURCE 
	
	if (dump_token)
	{
		printf("token: oNOT.\n");
	}
	return oNOT; 
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 360 "parser/spl.l"
{ 
	DUMP_SOURCE 
	
	if (dump_token)
	{
		printf("token: oBAND.\n");
	}
	return oBAND; 
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 370 "parser/spl.l"
{ 
	DUMP_SOURCE 
	
	if (dump_token)
	{
		printf("token: oBOR.\n");
	}
	return oBOR; 
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 380 "parser/spl.l"
{ 
	DUMP_SOURCE 
	
	if (dump_token)
	{
		printf("token: oBXOR.\n");
	}
	return oBXOR; 
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 390 "parser/spl.l"
{ 
	DUMP_SOURCE 
	
	if (dump_token)
	{
		printf("token: oBCOM.\n");
	}
	return oBCOM; 
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 400 "parser/spl.l"
{ 
	DUMP_SOURCE 
	
	if (dump_token)
	{
		printf("token: oRSH.\n");
	}
	return oRSH; 
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 410 "parser/spl.l"
{ 
	DUMP_SOURCE 
	
	if (dump_token)
	{
		printf("token: oLSH.\n");
	}
	return oLSH; 
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 420 "parser/spl.l"
{ 
	DUMP_SOURCE 
	
	if (dump_token)
	{
		printf("token: oSEMI.\n");
	}
	return oSEMI; 
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 430 "parser/spl.l"
{ 
	DUMP_SOURCE 
	
	if (dump_token)
	{
		printf("token: oCOLON.\n");
	}
	return oCOLON; 
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 440 "parser/spl.l"
{ 
	DUMP_SOURCE 
	
	if (dump_token)
	{
		printf("token: oDOTDOT.\n");
	}
	return oDOTDOT; 
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 450 "parser/spl.l"
{ 
	DUMP_SOURCE 
	
	if (dump_token)
	{
		printf("token: oDOT.\n");
	}
	return oDOT; 
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 460 "parser/spl.l"
{ 
	DUMP_SOURCE 
	
	if (dump_token)
	{
		printf("token: oQUOTE.\n");
	}
	return oQUOTE; 
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 470 "parser/spl.l"
{
	DUMP_SOURCE

	strncpy(yylval.p_char, yytext, NAME_LEN);
	return id_or_keyword(yytext);
}
	YY_BREAK
case 40:
/* rule 40 can match eol */
YY_RULE_SETUP
#line 477 "parser/spl.l"
{
	line_no++;
	line_pos = 0;
	line_buf[line_pos] = 0;
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 483 "parser/spl.l"
{
	BEGIN(star_slash_comment);
}
	YY_BREAK
case 42:
/* rule 42 can match eol */
YY_RULE_SETUP
#line 487 "parser/spl.l"
{
	/* eat anything that's not a '*' */
}
	YY_BREAK
case 43:
/* rule 43 can match eol */
YY_RULE_SETUP
#line 491 "parser/spl.l"
{
	/* eat up '*' not followed by '/'s */
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 495 "parser/spl.l"
{
	BEGIN(INITIAL);
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 499 "parser/spl.l"
{
	BEGIN(slash_slash_comment);
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 503 "parser/spl.l"
{
	/* eat anything that's not a '//' */
}
	YY_BREAK
case 47:
/* rule 47 can match eol */
YY_RULE_SETUP
#line 507 "parser/spl.l"
{
	line_no++;
	line_pos = 0;
	line_buf[line_pos] = 0;
	BEGIN(INITIAL);
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 514 "parser/spl.l"
{
	/* 匹配除了换行符之外的所有字符 */
	DUMP_SOURCE
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 518 "parser/spl.l"
ECHO;
	YY_BREAK
#line 1575 "parser/lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(star_slash_comment):
case YY_STATE_EOF(slash_slash_comment):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 190 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 190 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 189);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 518 "parser/spl.l"



/*
	type 用于自定义类型
	var 用于声明变量
	const 用于申明常量

	function 用于申明函数
	procedure 用于申明过程

	div 取整
	mod 取余

	repeat util 用于循环语句
	for to/downto do 用于循环语句
	while do 用于循环语句
	case of 条件跳转
	if then else if then else 条件跳转
	label goto 跳转
	begin 用于程序块或者流程控制语句，一般与end联合使用（for，function，while）
	end 主程序的end后面加'.'，函数，过程，和其他的加'；'（record定义、case of语句末尾），如果end后面有else，就什么都不加
*/

/* 匹配字符，对应的Token，Token类型*/
KEYENTRY Keytable[] = {
{"abs",		SYS_FUNCT,	fABS},
{"and",		kAND,		KEYWORD},
{"array",	kARRAY, 	KEYWORD},
{"begin",	kBEGIN, 	KEYWORD},
{"boolean", SYS_TYPE,	tBOOLEAN},
{"case",	kCASE, 		KEYWORD},
{"char",	SYS_TYPE,	tCHAR},
{"const",	kCONST,		KEYWORD},
{"cvb", TYPE_CONVERT, cvBOOLEAN},
{"cvf",	TYPE_CONVERT,	cvREAL},
{"cvi",	TYPE_CONVERT, cvINT},
{"div", 	kDIV,		KEYWORD},
{"do",		kDO, 		KEYWORD},
{"downto",	kDOWNTO,	KEYWORD},
{"else",	kELSE,		KEYWORD},
{"end", 	kEND, 		KEYWORD},
{"false",	SYS_CON,	cFALSE},
{"for",		kFOR,		KEYWORD},
{"function", kFUNCTION, KEYWORD},
{"if",		kIF, 		KEYWORD},
{"in", 		kIN,		KEYWORD},
{"integer", SYS_TYPE,	tINTEGER},
{"label",	kLABEL,		KEYWORD},
{"maxint", 	SYS_CON,	cMAXINT},
{"mod",		kMOD,		KEYWORD},
{"not", 	kNOT,		KEYWORD},
{"of",		kOF,		KEYWORD},
{"or",		kOR,		KEYWORD},
{"procedure", 	kPROCEDURE,	KEYWORD},
{"program", 	kPROGRAM, KEYWORD},
{"read",	SYS_READ,	pREAD},
{"readln", 	SYS_READ,	pREADLN},
{"real",	SYS_TYPE,	tREAL},
{"record", 	kRECORD,	KEYWORD},
{"repeat",	kREPEAT,	KEYWORD},
{"sqr",		SYS_FUNCT,	fSQR},
{"sqrt",	SYS_FUNCT,	fSQRT},
{"then",	kTHEN,		KEYWORD},
{"to",		kTO,		KEYWORD},
{"true",	SYS_CON,	cTRUE},
{"type",	kTYPE,		KEYWORD},
{"uchar",	SYS_TYPE,	tUCHAR},
{"uinteger",	SYS_TYPE,	tUINTEGER},
{"until",	kUNTIL,	KEYWORD},
{"var",		kVAR,		KEYWORD},
{"while",	kWHILE,		KEYWORD},
{"write",	SYS_PROC,	pWRITE},
{"writeln",	SYS_PROC,	pWRITELN},
{"----",	LAST_ENTRY,	KEYWORD}
};

struct {
	char *name;
	int key;
}key_to_name[] = {
	{"TYPE_CONVERT", TYPE_CONVERT },
	{"SYS_FUNCT",	SYS_FUNCT },
	{"kAND",		kAND },
	{"kARRAY",		kARRAY },
	{"kBEGIN",		kBEGIN },
	{"SYS_TYPE", 	SYS_TYPE },
	{"kCASE",		kCASE },
	{"kCONST",		kCONST },
	{"kDIV", 		kDIV },
	{"kDO",			kDO },
	{"kDOWNTO",		kDOWNTO },
	{"kELSE",		kELSE },
	{"kEND", 		kEND },
	{"SYS_CON",		SYS_CON },
	{"kFOR",		kFOR },
	{"kFUNCTION", 	kFUNCTION },
	{"kIF",			kIF },
	{"kIN", 		kIN },
	{"kLABEL",		kLABEL },
	{"kMOD",		kMOD },
	{"kNOT", 		kNOT },
	{"kOF",			kOF },
	{"kOR",			kOR },
	{"kPROCEDURE", 	kPROCEDURE },
	{"kPROGRAM", 	kPROGRAM },
	{"SYS_READ",		SYS_READ },
	{"kRECORD", 	kRECORD },
	{"kREPEAT",		kREPEAT },
	{"kTHEN",		kTHEN },
	{"kTO",			kTO },
	{"kTYPE",		kTYPE },
	{"kUNTIL",		kUNTIL },
	{"kVAR",		kVAR },
	{"kWHILE",		kWHILE },
	{"SYS_PROC",	SYS_PROC },
	{"LAST_ENTRY",	LAST_ENTRY }
};

static char *get_name_by_key(int key)
{
	int i;

	for (i = 0; i < sizeof(key_to_name) / sizeof(key_to_name[0]); i++)
	{
		if (key_to_name[i].key == key)
			return key_to_name[i].name;
	}
	return "bad key";
}

static int id_or_keyword(char *lex)
{
	int left = 0, right = Keytable_size;
	int mid = (left + right) / 2;
	char *p;

	if (!Keytable_size)
	{
		internal_error("Key table size not known.\n");
		exit(0);
	}
	
	/* 转化为小写（pascal语言的token是忽略大小写的） */
	for (p = lex; *p; p++)
		*p = tolower(*p);

	/* 二分法查找 */
	while (mid != left && mid != right)
	{
		if (!strcmp(Keytable[mid].name, lex))
		{
			if (dump_token)
			{
				printf("token: %s ", get_name_by_key(Keytable[mid].key));
			}

			if (Keytable[mid].key == SYS_FUNCT
				|| Keytable[mid].key == SYS_PROC)
			{
				/* 系统函数或者系统调用 */
				yylval.p_lex = &Keytable[mid];

				if (dump_token)
				{
					printf(",yylval.p_lex = &Keytable[%d]", mid);
				}
			}
			else if(Keytable[mid].key == SYS_READ)
			{
				/* read function */
				yylval.p_lex = &Keytable[mid];

				if (dump_token)
				{
					printf(",yylval.p_lex = &Keytable[%d]", mid);
				}
			}
			else if(Keytable[mid].key == TYPE_CONVERT)
			{
				/* type conversion */
				yylval.p_lex = &Keytable[mid];
				if (dump_token)
				{
					printf(",yylval.p_lex = &Keytable[%d]", mid);
				}
			}
			else if (Keytable[mid].key == SYS_CON)
			{
				/* true、false或者maxint */
				yylval.num = Keytable[mid].attr;

				if (dump_token)
				{
					printf(",yylval.p_num = Keytable[%d].atrr = %d", mid, Keytable[mid].attr);
				}
			}
			else if (Keytable[mid].key == SYS_TYPE)
			{
				/* real、integer、char、boolean */
				strncpy(yylval.p_char, yytext, NAME_LEN);

				if (dump_token)
				{
					printf(",yylval.p_char = %s", yylval.p_char);
				}
			}

			if (dump_token)
				printf(".\n");

			return Keytable[mid].key;
		}
		else if (strcmp(Keytable[mid].name, lex) < 0)
			left = mid;
		else if (strcmp(Keytable[mid].name, lex) > 0)
			right = mid;

		mid = (left + right) / 2;
	}

	if (dump_token)
	{
		printf("token: yNAME, yylval.p_char = %s.\n", yylval.p_char);
	}

	/* 变量名称 */
	return yNAME;
}

int get_keytable_size()
{
	int i;

	Keytable_size = 0;

	for (i = 0; ; Keytable_size++, i++)
	{
		if (Keytable[i].key == LAST_ENTRY)
			break;
	}

	return 0;
}

int yywrap() 
{
	return 1;
}


